trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build .NET Core app'
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: CopyFiles@2
  displayName: 'Copy build artifacts'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/bin/$(Build.Configuration)/net5.0'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureFileCopy@4
  displayName: 'Copy artifacts to Azure Files'
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)'
    azureSubscription: 'bea2acb9-69b6-4eed-9b6a-5add7e8e8f93'
    destination: 'chandra'
    filePattern: '**/*'
    cleanTargetBeforeCopy: true
    preserveTimestamp: true
