name: my workflow
on: 
  push:
    branches:
    - master
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Build
        run: dotnet build TestApplication.sln --configuration Release  
